[[rss]]
group = "לבונטין 7"
url = "https://levontin7.com/events/rss"
image = "div.fat-event-thumb"
refresh = "5m"

[[rss]]
group = "אוזן"
url = "https://ozentlv.com/event/rss"
image = ".ozen-section_event__body-thumbnail img"
refresh = "5m"

# Define scraper by jquery selectors
[[generic]]
group = "בארבי"
url = "https://www.barby.co.il"
title = ".inlineDefNameBig, .inlineDefName"
desc = ".show1-description"
image = ".showCatMainImgNP, .showCatMainImg"
refresh = "5m"

[[generic]]
group = "תדר"
url = "https://www.teder.fm/"
title = ".item-future .title"
desc = ".content-body"
image = ".content-image-container img"
refresh = "5m"
